### ISSUE TITLE
rsyslog server can't write logs when using privilege separation

### ISSUE THREAD

**Issue by alexanderBendo** [opscode-cookbooks/rsyslog#70]
In Ubuntu >= 11.04 the cookbook correctly sets the user to *syslog* but the *log_dir* directory always has owner *root* with mode 0755. In such cases rsyslog can't write any log file. Maybe the ```log_dir``` directory resource should use ```node['rsyslog']['user']``` as the owner.

**Comment by eheydrick** [comment]
https://github.com/opscode-cookbooks/rsyslog/pull/51 addresses the incorrect privileges when using priv sep.

**Comment by eheydrick** [comment]
Actually this has been fixed in master with https://github.com/opscode-cookbooks/rsyslog/commit/386a413d117c078121784fd7c7ec4567d8fbfc0e.
