### ISSUE TITLE
Rsyslog Service Not Defined

### ISSUE THREAD

**Issue by bassrock** [opscode-cookbooks/rsyslog#77]
I am using the file_input provider and I keep getting this error not he notify restart:

```chef
had an error: Chef::Exceptions::ResourceNotFound: Cannot find a resource matching service[rsyslog] (did you define it first?)
```

Cookbook Trace:
---------------
```
/var/lib/aws/opsworks/cache.stage2/cookbooks/rsyslog/providers/file_input.rb:31:in `block (2 levels) in class_from_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/rsyslog/providers/file_input.rb:20:in `block in class_from_file'
```

**Comment by tas50** [comment]
Is the default rsyslog recipe including somewhere on your runlist?  Without that the service is never defined and chef-client doesn't know what to notify for a restart.

**Comment by bassrock** [comment]
Yes. I am using this on Opsworks in the before_symlink hook. I have added rsyslog and rsyslog::client to the deploy layers and see it on the run list.

**Comment by tas50** [comment]
I just merged a pull request that I believe will fix this.  I'll see if I can get a release out today.

**Comment by bassrock** [comment]
Sweet Thanks!
